system_info:
  system_id: "71_2537_62"
  num_site: 10

agent_settings:
  gpt_version: "gpt-4o"
  gnn_model: "EquiformerV2-31M-S2EF-OC20-All+MD"
  mode: "llm-guided_site_heuristic_placement"
  critic_activate: true
  reviewer_activate: true

paths:
  question_path: "/home/hoon/llm-agent/adsorb/reasoning.txt"
  knowledge_path: "/home/hoon/llm-agent/adsorb/knowledge.txt"
  metadata_path: "/home/hoon/llm-agent/adsorb/data/processed/updated_sid_to_details.pkl"
  bulk_db_path: "/home/hoon/llm-agent/fairchem-forked/src/fairchem/data/oc/databases/pkls/bulks.pkl"
  ads_db_path: "/home/hoon/llm-agent/fairchem-forked/src/fairchem/data/oc/databases/pkls/adsorbates.pkl"
  save_dir: "/home/hoon/llm-agent/results/71_2537_62/"
